[package]
name = "react_demo_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.0"
ic-cdk = "0.12.0"
ic-siwe = { path = "../../../ic-siwe-rust" }
serde = "1.0.193"
serde_json = "1.0.108"
ic-stable-structures = "0.6.0"
serde_bytes = "0.11"
